@startuml
!define ER

entity User {
    *id : int
    username : string
    email : string
    password : string
    status : enum
}

entity House{
    *id : int
    name : string
    user_id : int
}

entity Location {
    *id : int
    name : string
    house_id : int
}

entity Device {
    *id : int
    type_id : int
    status : enum
    model : string
    name : string
    serial_number : string
    mac_address : string
    location_id : int
    manufacturer_id : int
    firmware_id : int
}

entity Scenario {
    *id : int
    trigger_id : int
    device_id : int
    action_id : int
}

entity Trigger{
    *id : int
    scenario_id : int
    type : enum(time, event)
    parameters : text
}

entity Action {
    *id : int
    scenario_id : int
    device_type_id : int
    type : text
    parameters : text
}

entity DeviceType {
    *id : int
    code : string
    name : string
}

entity Manufacturer {
    *id : int
    name : string
    country : string
}

entity Firmware {
    *id : int
    version : string
    release_date : date
    description : string
}

User ||--o{ House : user
House ||--o{ Location : location
Location ||--o{ Device : device
DeviceType ||--o{ Device : type
Firmware ||--o{ Device : firmware
Manufacturer ||--o{ Device : manufacturer
Scenario ||--o{ Device : type
Scenario ||--o{ Trigger : scenario
Action ||--o{ Scenario : action 

@enduml